const ROLES = Object.freeze({
  OWNER: 'OWNER',
  MANAGER: 'MANAGER',
  STAFF: 'STAFF',
  ACCOUNTANT: 'ACCOUNTANT',
  ADMIN: 'ADMIN',
});

const DATA_SOURCE_TYPES = Object.freeze([
  'MANUAL',
  'CSV',
  'EXCEL',
  'SIX_STAR_POS',
  'SIX_STAR_SUPPLIERS',
  'EXTERNAL_POS',
  'API',
  'IMPORT',
]);

const DATA_PREFERENCES = Object.freeze(['HAVE_DATA', 'MANUAL_ENTRY', 'CONNECT_POS_LATER']);

const RECOMMENDATION_ACTIONS = Object.freeze([
  'ORDER', 'REORDER', 'DO_NOT_BUY', 'STOP_BUYING', 'DISCOUNT', 'REPRICE',
  'TRANSFER', 'INVEST', 'SAVE_CASH', 'PROMOTE', 'CLEAR_STOCK', 'FIND_SUPPLIER',
  'EXPAND', 'WAIT', 'REDUCE_STOCK',
]);

module.exports = { ROLES, DATA_SOURCE_TYPES, DATA_PREFERENCES, RECOMMENDATION_ACTIONS };